name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
      WORKFLOW_LEVEL_VAR1: This_is_workflow_level_env_variable
jobs:
  test:
    
    environment: testing
    env: 
      TEST_JOB_LEVEL_VAR: SomeValuethatwillnotbeavailablefromDeployJob
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      DEPLOY_JOB_LEVEL_VAR: DEPLOY_JOB_LEVEL_VAR
    steps:
      - name: Output information
        run: |        
          echo "..."
          echo " MONGODB_USERNAME: $MONGODB_USERNAME"
          echo  " MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }}"
          echo " PORT: $PORT"
          echo "$WORKFLOW_LEVEL_VAR1"
          echo "$DEPLOY_JOB_LEVEL_VAR"
          echo "$TEST_JOB_LEVEL_VAR"
      - name: Output Environment Variables
        run: |        
          echo "..."
          echo " GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo  " GITHUB_ENV: $GITHUB_ENV"
          echo " GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_RETENTION_DAYS $GITHUB_RETENTION_DAYS"   
          echo "Open Secret: {{ secrets.OPEN_SECRET }}"
          echo " This is repo level env variable. This is : ${{ env.ENVIRONMENT }} environment "
